{
 "title": "Service",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(process_start_time_seconds{status=\"running\"},service_id)"
    }
   },
   {
    "name": "replicas",
    "label": "replicas",
    "query": {
     "query": "label_values({service_id=\"$service\"},replica_no)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_start_time_seconds{service_id=\"$service\", instance=\"server:8001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{service_id=\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STDERR",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"slurm-stderr\", filename=~\"/logs/.*${service}.*\"}"
    }
   ]
  },
  {
   "title": "STDOUT",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"slurm-stdout\", filename=~\"/logs/.*${service}.*\"}"
    }
   ]
  },
  {
   "title": "Virtual memory used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{service_id=\"$service\", status=\"running\"}",
     "legendFormat": "Virtual memory - {{replica_no}}"
    }
   ]
  },
  {
   "title": "Resident memory used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service_id=\"$service\", status=\"running\"}",
     "legendFormat": "Virtual memory - {{replica_no}}"
    }
   ]
  },
  {
   "title": "CPU time active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_start_time_seconds{service_id=\"$service\", status=\"running\"}[$__interval])",
     "legendFormat": "Run time"
    },
    {
     "expr": "irate(process_cpu_seconds_total{service_id=\"$service\", status=\"running\"}[$__interval])",
     "legendFormat": "Total time"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Active FDs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_open_fds{service_id=\"$service\", status=\"running\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "process_max_fds{service_id=\"$service\", status=\"running\"}",
     "legendFormat": "Max FDs"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  { "title": "Python", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Python version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_info{status=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of objects collected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 44 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{service_id=~\"$service\", status=\"running\"}",
     "legendFormat": "generation = {{generation}} - {{replica_no}}"
    }
   ]
  },
  {
   "title": "Number of uncollectable objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total{service_id=~\"$service\", status=\"running\"}",
     "legendFormat": "generation = {{generation}} - {{replica_no}}"
    }
   ]
  },
  {
   "title": "Number of total collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 44 },
   "targets": [
    {
     "expr": "python_gc_collections_total{service_id=~\"$service\", status=\"running\"}",
     "legendFormat": "generation = {{generation}} - {{replica_no}}"
    }
   ]
  },
  {
   "title": "Heatmap request latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_request_duration_highr_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs - $replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }, "repeat": "replicas" },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"vllm-log\", filename=~\"/logs/vllm_${service}_replica_0\\\\.log\"} | logfmt | label_format level=detected_level"
    }
   ]
  }
 ]
}