{
 "title": "Prometheus",
 "description": "Adapted from https://github.com/prometheus/test-infra/blob/master/prombench/manifests/cluster-infra/dashboards/prombench.json",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Prometheus Info",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "prometheus_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}",
     "legendFormat": "{{job}} - Uptime"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"prometheus\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Head Time series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"prometheus\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Active Appenders",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_active_appenders{job=\"prometheus\"}",
     "legendFormat": "{{instance}} - Head Appenders"
    }
   ]
  },
  {
   "title": "Samples Appended/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"prometheus\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Chunks Created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_created_total{job=\"prometheus\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Chunks Removed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_removed_total{job=\"prometheus\"}[1m])",
     "legendFormat": "{{instance}} - Removed"
    }
   ]
  },
  {
   "title": "Head Time Range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_min_time{job=\"prometheus\"}",
     "legendFormat": "{{instance}} - min time"
    },
    { "expr": "time() * 1000", "legendFormat": "DB time" },
    {
     "expr": "prometheus_tsdb_head_max_time{job=\"prometheus\"}",
     "legendFormat": "{{instance}} - max time"
    }
   ]
  },
  {
   "title": "Avg Head GC Time/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum{job=\"prometheus\"}[1m]) / rate(prometheus_tsdb_head_gc_duration_seconds_count{job=\"prometheus\"}[1m])",
     "legendFormat": "{{instance}} - GC Time/s"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=\"prometheus\"}",
     "legendFormat": "{{instance}} - Blocks Loaded"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\"}[1m])",
     "legendFormat": "{{instance}} - Allocated Bytes/s"
    }
   ]
  },
  {
   "title": "TSDB Reloads/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - Reloads"
    }
   ]
  },
  {
   "title": "TSDB Problems/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_corruptions_total{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - WAL Corruptions"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - Reload Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_head_series_not_found{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - Head Series Not Found"
    },
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - Compaction Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - Retention Cutoff Failures"
    }
   ]
  },
  {
   "title": "Retention Cutoffs/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_size_retentions_total{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - (size)"
    },
    {
     "expr": "rate(prometheus_tsdb_time_retentions_total{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - (time)"
    }
   ]
  },
  {
   "title": "WAL Fsync Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum{job=\"prometheus\"}[1m]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count{job=\"prometheus\"}[1m])",
     "legendFormat": "{{instance}} - Fsync Latency"
    }
   ]
  },
  {
   "title": "WAL Truncate Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_truncate_duration_seconds_sum{job=\"prometheus\"}[1m]) / rate(prometheus_tsdb_wal_truncate_duration_seconds_count{job=\"prometheus\"}[1m])",
     "legendFormat": "{{instance}} - Truncate Latency"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Bytes/Sample",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_size_sum{job=\"prometheus\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\"}[10m]) or rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"prometheus\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - Bytes/Sample"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Time Range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_range_sum{job=\"prometheus\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_range_count{job=\"prometheus\"}[10m]) or rate(prometheus_tsdb_compaction_chunk_range_seconds_sum{job=\"prometheus\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_range_seconds_count{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - Chunk Time Range"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Samples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_count{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - Chunk Samples"
    }
   ]
  },
  {
   "title": "Compactions/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_total{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}} - Compactions"
    }
   ]
  },
  {
   "title": "Avg Compaction Time/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{job=\"prometheus\"}[10m]) / rate(prometheus_tsdb_compaction_duration_seconds_count{job=\"prometheus\"}[10m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"prometheus\"}[1m])",
     "legendFormat": "{{instance}} - Irate"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[5m])",
     "legendFormat": "{{instance}} - 5m rate"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "{{instance}} - RSS"
    },
    {
     "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\"}",
     "legendFormat": "{{instance}} - Target heap size"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"prometheus\"}",
     "legendFormat": "{{instance}} - Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}",
     "legendFormat": "{{instance}} - Allocated"
    }
   ]
  },
  {
   "title": "HTTP requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\"}[1m])",
     "legendFormat": "{{instance}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Avg HTTP request latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\"}[1m]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\"}[1m])",
     "legendFormat": "{{instance}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Avg query engine timings/s - prepare_time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",slice=\"prepare_time\"}[1m]) / rate(prometheus_engine_query_duration_seconds_count{job=\"prometheus\",slice=\"prepare_time\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg query engine timings/s - inner_eval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",slice=\"inner_eval\"}[1m]) / rate(prometheus_engine_query_duration_seconds_count{job=\"prometheus\",slice=\"inner_eval\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg query engine timings/s - queue_time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",slice=\"queue_time\"}[1m]) / rate(prometheus_engine_query_duration_seconds_count{job=\"prometheus\",slice=\"queue_time\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg query engine timings/s - result_sort",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",slice=\"result_sort\"}[1m]) / rate(prometheus_engine_query_duration_seconds_count{job=\"prometheus\",slice=\"result_sort\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TSDB Isolation Watermarks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_isolation_low_watermark",
     "legendFormat": "{{instance}} - low watermark"
    },
    {
     "expr": "prometheus_tsdb_isolation_high_watermark",
     "legendFormat": "{{instance}} - high watermark"
    }
   ]
  },
  {
   "title": "Evaluation time of rule groups/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_duration_seconds_sum{job=\"prometheus\"}[1m])",
     "legendFormat": "{{instance}} - Rule evaluation duration"
    }
   ]
  },
  {
   "title": "TSDB Isolation Watermarks Difference",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_isolation_high_watermark - prometheus_tsdb_isolation_low_watermark",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}